### ISSUE TITLE
attempt to call a nil value

### ISSUE THREAD

**Issue by Briningr** [VORPCORE/vorp_bossmanager#3]
Just this past week we started getting this error for boss_manager. The screenshot is from our F8 list.
![2023-12-26_12-33-45](https://github.com/VORPCORE/vorp_bossmanager/assets/151418234/cfa349ec-256c-4cb2-9441-bc2f491b451f)

**Comment by Briningr** [comment]
This is still throwing errors and causing, I believe, the following errors from the language files.
![2024-01-04_08-39-54](https://github.com/VORPCORE/vorp_bossmanager/assets/151418234/685ba940-2f1a-4054-bfa4-de5b91e782a0)

**Comment by MaldoJ** [comment]
I am getting the same as Briningr:

`
[     76844] [b1491_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @vorp_bossmanager/locale.lua:14: attempt to concatenate a nil value (field 'Locale')^7
[     76844] [b1491_GTAProce]             MainThrd/ ^3> _^7 (^5@vorp_bossmanager/locale.lua^7:14)
[     76844] [b1491_GTAProce]             MainThrd/ ^3> _U^7 (^5@vorp_bossmanager/locale.lua^7:20)
[     76844] [b1491_GTAProce]             MainThrd/ ^3> fn^7 (^5@vorp_bossmanager/client.lua^7:40)
`

**Comment by JustRoys** [comment]
You are missing a translation(s)

**Comment by yaboibutt3r** [comment]
same issue here... literally the one script thats sending issues for me

**Comment by outsider31000** [comment]
this script does not work with the current framework state. do not use it
